const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const {createReader,derive}=require('./dist/assets/ring-accounting.js');
const {fresh}=require('./dist/assets/ring-project.js');
let reads=0;
const record={...fresh('pet'),id:'test',endedAt:new Date().toISOString(),costs:[{name:'武器',price:20,score:2}],rewards:[{kind:'书',name:'剑',level:'100',price:100,quantity:1}]};
const reader=createReader(()=>{reads++;return [record]});
const first=reader.days();
for(let i=0;i<100;i++)assert.equal(reader.days(),first);
assert.equal(reads,1);
record.rewards[0].price=120;reader.invalidate();
assert.equal(reader.days()[Object.keys(first)[0]].revenue,120);
assert.equal(reads,2);
const s=fs.readFileSync('dist/assets/index-CGBfnq9b.js','utf8');
const iconStart=s.indexOf('Om={')+3,iconEnd=s.indexOf('},si={',iconStart)+1;
const Om=vm.runInNewContext('('+s.slice(iconStart,iconEnd)+')');
const itemStart=s.indexOf(',In=[')+4,itemEnd=s.indexOf(';function Wm()',itemStart);
const stored=new Map();let writes=0;
const context={console,Om,si:{ITEMS:'items'},localStorage:{getItem:key=>stored.get(key)||null,setItem:(key,value)=>{writes++;stored.set(key,value)}}};
vm.createContext(context);
vm.runInContext('function F(name){return Om[name.replace(/\.[^/.]+$/,"")]||""}const In='+s.slice(itemStart,itemEnd)+';',context);
const helperStart=s.indexOf('function storeChanged('),helperEnd=s.indexOf('function ringRawDaily()',helperStart);
vm.runInContext(s.slice(helperStart,helperEnd),context);
vm.runInContext('var original=In.map(item=>({...item,price:item.id===1?12.3456:0}));',context);
const before=vm.runInContext('JSON.stringify(original)',context);
stored.set('items',before);
vm.runInContext('sr(Nm())',context);
const after=stored.get('items');
assert.ok(after.length<before.length/10);
assert.equal(writes,1);
vm.runInContext('sr(Nm());sr(Nm())',context);
assert.equal(writes,1,'Unchanged prices must not rewrite storage');
assert.equal(vm.runInContext('Nm()[0].price',context),12.3456);
assert.equal(vm.runInContext('Nm()[0].icon',context),Om['60武器']);
vm.runInContext('var custom=Nm();custom[0].icon="data:image/png;base64,custom";sr(custom)',context);
assert.equal(vm.runInContext('Nm()[0].icon',context),'data:image/png;base64,custom');
const errorReader=createReader(()=>{throw new Error('broken')});
assert.throws(()=>errorReader.days(),/broken/);
const big=Array.from({length:200},(_,i)=>({...record,id:'bench-'+i,costs:Array.from({length:100},()=>({name:'武器',price:20,score:2}))}));
const {performance}=require('node:perf_hooks');
let start=performance.now();for(let i=0;i<20;i++)derive(big);const baseline=performance.now()-start;
const bench=createReader(()=>big);start=performance.now();for(let i=0;i<20;i++)bench.days();const optimized=performance.now()-start;
console.log('PASS: icon migration preserves prices/artwork, unchanged-write suppression, cache reuse/invalidation and error handling.');
console.log(`Built-in item storage: ${before.length} -> ${after.length} characters (${(100-after.length/before.length*100).toFixed(1)}% reduction).`);
console.log(`Synthetic benchmark (200 rounds x 100 costs, 20 queries): ${baseline.toFixed(1)}ms -> ${optimized.toFixed(1)}ms.`);
